FROM apache/spark:3.5.3

USER root
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install pyspark==3.5.3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PYSPARK_PYTHON=/usr/bin/python3
ENV PYSPARK_DRIVER_PYTHON=/usr/bin/python3

USER spark