FROM apache/superset:latest

USER root

RUN apt-get update && apt-get install -y wget && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    python3 -m pip install --no-cache-dir clickhouse-connect && \
    rm get-pip.py && \
    apt-get purge -y wget && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

USER superset