services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network
      # - bigdata_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_webserver
    hostname: airflow-webserver
    # user: "50000:50000"
    depends_on:
      postgres:
        condition: service_healthy
      namenode:
        condition: service_healthy
    environment:
      PYSPARK_PYTHON: /usr/bin/python3
      # PYSPARK_PYTHON: python3
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD:-airflow}@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY:-secret}
      AIRFLOW__WEBSERVER__RBAC: 'True'
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD:-admin}
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__LOG_FILENAME_TEMPLATE: "{{ ti.dag_id }}/{{ ti.task_id }}/{{ ts }}/{{ try_number }}.log"
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 300
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 60
      AIRFLOW__SCHEDULER__PARSING_PROCESSES: 2
      AIRFLOW__SCHEDULER__DAG_FILE_PROCESSOR_TIMEOUT: 150
      AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: 30
      AIRFLOW__CORE__KEEPALIVE_STARET_DELAY: 30
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_RETRIES: 10
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./spark:/opt/spark-apps
      - ./init-airflow.sh:/init-airflow.sh
      - ./hadoop_config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop_config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      # - ./hadoop_config:/opt/bitnami/spark/conf/hadoop/
    ports:
      - "8081:8080"
    command: >
      bash -c "/init-airflow.sh && airflow webserver"
    # command: >
    #   bash -c "
    #     mkdir -p /opt/airflow/logs /opt/airflow/logs/scheduler &&
    #     chmod -R 777 /opt/airflow/logs &&
    #     /init-airflow.sh &&
    #     airflow webserver
    #   "
    networks:
      - airflow_network
      - bigdata_network
    restart: on-failure

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_scheduler
    # user: "50000:50000"
    depends_on:
      - airflow-webserver
    environment:
      # PYSPARK_PYTHON: python3
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD:-airflow}@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 300
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 60
      AIRFLOW__SCHEDULER__PARSING_PROCESSES: 2
      AIRFLOW__SCHEDULER__DAG_FILE_PROCESSOR_TIMEOUT: 150
      AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: 30
      AIRFLOW__CORE__KEEPALIVE_STARET_DELAY: 30
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_RETRIES: 10
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./spark:/opt/spark-apps
      - ./hadoop_config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop_config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      # - ./hadoop_config:/opt/bitnami/spark/conf/hadoop/
    command: airflow scheduler
    # command: >
    #   bash -c "
    #     mkdir -p /opt/airflow/logs /opt/airflow/logs/scheduler &&
    #     chmod -R 777 /opt/airflow/logs &&
    #     airflow scheduler
    #   "
    ports:
      - "7001:7001"
      - "7002:7002"
    networks:
      - bigdata_network
      - airflow_network
    restart: on-failure

  namenode:
    image: apache/hadoop:3.3.5
    container_name: namenode
    hostname: namenode
    user: root
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/namenode
      - ./hadoop_config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop_config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      # - ./hadoop_config/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties
      # - ./hadoop_config:/opt/bitnami/spark/conf/hadoop/
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - CLUSTER_NAME=test
      # - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
      # - HDFS_CONF_dfs_namenode_heartbeat_recheck-interval=10000 
      # - HDFS_CONF_dfs_heartbeat_interval=1
    ports:
      - "9870:9870"
      - "9000:9000"
    # command: ["bash", "-c", "hdfs namenode"]
    # command: >
    #   bash -c "
    #       if [ ! -d /hadoop/dfs/name/current ]; then
    #         echo 'Formatting NameNode...'
    #         hdfs namenode -format -force -nonInteractive
    #       fi
    #       hdfs namenode
    #     "
    command: >
      bash -c "
        echo '=== Checking NameNode directories ==='
        mkdir -p /opt/hadoop/data/namenode
        chmod -R 777 /opt/hadoop/data/namenode
        
        echo '=== Creating archive and success folder ==='
        hdfs dfs -mkdir -p /user/airflow/archive
        hdfs dfs -mkdir -p /user/airflow/success

        echo '=== Preparing for airflow ==='
        hdfs dfs -mkdir -p /user/airflow/stream_input
        hdfs dfs -chmod -R 777 /user
        
        if [ ! -d /opt/hadoop/data/namenode/current ]; then
          echo '=== Formatting NameNode ==='
          echo 'Y' | hdfs namenode -format -force
          echo '=== NameNode formatted ==='
        fi
        
        echo '=== Starting NameNode ==='
        hdfs namenode

        hdfs dfs -chown -R airflow:supergroup /user/airflow
      "
    # command: >
    #   bash -c "
    #     if [ ! -d /opt/hadoop/data/namenode/current ]; then
    #       echo '=== Formatting NameNode ==='
    #       hdfs namenode -format -force -nonInteractive
    #     fi
        
    #     hdfs namenode &
        
    #     echo '=== Waiting for NameNode to be ready ==='
    #     until hdfs dfsadmin -safemode wait; do
    #       echo 'NameNode is still starting up...'
    #       sleep 5
    #     done
    #     echo '=== NameNode is up ==='

    #     hdfs dfs -mkdir -p /user/airflow/success
    #     hdfs dfs -mkdir -p /user/airflow/archive
    #     hdfs dfs -mkdir -p /user/airflow/stream_input
    #     hdfs dfs -chmod -R 777 /user
    #     hdfs dfs -chown -R root:root /user/airflow
    #     echo '=== HDFS success, archive, stream_input folders created ==='
        
    #     wait
    #   "
    networks:
      - bigdata_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 10s
      timeout: 5s
      retries: 5

  datanode:
    image: apache/hadoop:3.3.5
    container_name: datanode
    hostname: datanode
    user: root
    volumes:
      - ./hadoop_datanode:/opt/hadoop/data/datanode
      - ./hadoop_config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop_config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      # - ./hadoop_config:/opt/bitnami/spark/conf/hadoop/
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - CLUSTER_NAME=test
      # - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
      # - HDFS_CONF_dfs_namenode_heartbeat_recheck-interval=10000 
      # - HDFS_CONF_dfs_heartbeat_interval=1
    depends_on:
      - namenode
    # command: ["bash", "-c", "hdfs datanode"]
    # command: >
    #   bash -c "
    #     echo 'Waiting for NameNode to start...'
    #     sleep 10
    #     echo 'Starting DataNode...'
    #     hdfs datanode
    #   "
    command: >
      bash -c "
        echo '=== Waiting for NameNode ==='
        sleep 15
        mkdir -p dags logs spark hadoop_config hadoop_namenode hadoop_datanode  
        chmod -R 777 logs hadoop_namenode hadoop_datanode
        
        echo '=== Creating DataNode directories ==='
        mkdir -p /opt/hadoop/data/datanode
        chmod -R 777 /opt/hadoop/data/datanode
        
        echo '=== Checking DataNode directory ==='
        ls -la /opt/hadoop/data/datanode
        
        echo '=== Starting DataNode ==='
        hdfs datanode
      "
    networks:
      - bigdata_network

  datanode2:
    image: apache/hadoop:3.3.5
    container_name: datanode2
    hostname: datanode2
    user: root
    volumes:
      - ./hadoop_datanode2:/opt/hadoop/data/datanode
      - ./hadoop_config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop_config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - CLUSTER_NAME=test
      # - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
      # - HDFS_CONF_dfs_namenode_heartbeat_recheck-interval=10000 
      # - HDFS_CONF_dfs_heartbeat_interval=1
    depends_on:
      - namenode
    # command: >
    #   bash -c "
    #     sleep 15 &&
    #     mkdir -p /opt/hadoop/data/datanode &&
    #     chmod -R 777 /opt/hadoop/data/datanode &&
    #     hdfs datanode
    #   "
    command: >
      bash -c "
        echo '=== Waiting for NameNode ==='
        sleep 15
        
        echo '=== Creating DataNode directories ==='
        mkdir -p /opt/hadoop/data/datanode
        chmod -R 777 /opt/hadoop/data/datanode
        
        echo '=== Checking DataNode directory ==='
        ls -la /opt/hadoop/data/datanode
        
        echo '=== Starting DataNode ==='
        hdfs datanode
      "
    networks:
      - bigdata_network

  spark-master:
    # image: apache/spark:3.5.3
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark_master
    hostname: spark-master
    volumes:
      # - ./hadoop_config/core-site.xml:/opt/bitnami/spark/conf/hadoop/core-site.xml
      # - ./hadoop_config/hdfs-site.xml:/opt/bitnami/spark/conf/hadoop/hdfs-site.xml
      - ./hadoop_config:/opt/bitnami/spark/conf/hadoop/
      - ./spark:/opt/spark-apps
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_DAEMON_MEMORY=512m
      # - SPARK_LOCAL_IP=0.0.0.0
      # - SPARK_PUBLIC_DNS=spark-master
      - HADOOP_CONF_DIR=/opt/bitnami/spark/conf/hadoop
      - PATH=/opt/spark/bin:$PATH
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
      # - PYSPARK_PYTHON=/usr/bin/python3.11
      # - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.11
    ports:
      - "8082:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    networks:
      - bigdata_network
    restart: on-failure

  spark-worker:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.spark-worker
    build:
      context: .
      dockerfile: Dockerfile.spark
    # container_name: spark_worker
    depends_on:
      - spark-master
    volumes:
      # - ./hadoop_config/core-site.xml:/opt/bitnami/spark/conf/hadoop/core-site.xml
      # - ./hadoop_config/hdfs-site.xml:/opt/bitnami/spark/conf/hadoop/hdfs-site.xml
      - ./hadoop_config:/opt/bitnami/spark/conf/hadoop/
      - ./spark:/opt/spark-apps
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_PORT=7078
      - SPARK_WORKER_WEBUI_PORT=8083
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_DAEMON_MEMORY=512m
      # - SPARK_LOCAL_IP=0.0.0.0
      # - SPARK_PUBLIC_DNS=spark-worker
      - HADOOP_CONF_DIR=/opt/bitnami/spark/conf/hadoop
      - PATH=/opt/spark/bin:$PATH
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
      # - PYSPARK_PYTHON=/usr/bin/python3.11
      # - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.11
      - SPARK_LOCAL_DIRS=/tmp/spark
    # ports:
    #   - "8083:8083"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    # command: >
    #   bash -c "
    #     pip install pyspark==3.5.3 &&
    #     /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    #   "
    networks:
      - bigdata_network
    restart: on-failure

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9001:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_logs:/var/log/clickhouse
    networks:
      - bigdata_network

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY:-secret}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD:-admin}
    volumes:
      - ./superset_init.sh:/app/superset_init.sh
      - ./superset_home:/app/superset_home
    ports:
      - "8088:8088"
    entrypoint: /app/superset_init.sh
    depends_on:
      - clickhouse
    networks:
      - bigdata_network

volumes:
  postgres_data:
  logs:

networks:
  airflow_network:
    driver: bridge
  bigdata_network:
    driver: bridge