# Spark configuration
spark.master                     spark://spark-master:7077
spark.executor.memory            512m
spark.executor.cores             1
spark.driver.memory              512m
spark.dynamicAllocation.enabled  false
spark.sql.adaptive.enabled       false

# Python settings
spark.pyspark.python             /usr/bin/python3
spark.pyspark.driver.python      /usr/bin/python3
spark.executorEnv.PYSPARK_PYTHON /usr/bin/python3
spark.executorEnv.PYTHONPATH     /opt/spark/python/lib/pyspark.zip:/opt/spark/python/lib/py4j-0.10.9.7-src.zip
