# Spark configuration
spark.master                     spark://spark-master:7077
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://namenode:9000/spark-logs
spark.history.fs.logDirectory    hdfs://namenode:9000/spark-logs
spark.sql.adaptive.enabled       false
spark.dynamicAllocation.enabled  false
spark.executor.memory            512m
spark.executor.cores             1
spark.driver.memory              512m
spark.cores.max                  1
